name : Continuous Integration

   on :
       pull_requets :
         branches : [main] 

jobs :
  build-and-test :
     runs-on : ubuntu-latest

     steps :
        uses : actions/checkout@v3
        
        
        name : Set up Node.js
        uses : actions/setuo-node@v3
        with :
           node-version : "16"
        
        name : Install dependecies
        run : npm install

        name : Build
        run : npm run build

        name : Run tests
        run : npm test

        name : Send email notification if build fail
        if : failure()
        uses : dawidd6/action-send-nail@v3
        with :
           server_address : smtp.gmail.com
           server_port : 587
           username : ${{ secrets.EMAIL_USERNAME}}
           password : ${{ secrets.EMAIL_PASSWORD}}
           subject : Github Actions - Build Failure
           body :
               The recent build has failed.

               - Repository : ${{ github.repository}}
               - Workflow : ${{ github.workflow }}
               - PR Link : ${{ github.event.pull_request.html_url }}

               Please check the details in the Github Actions logs.
            to : papipaid98@gmail.com
            from: CI Bot <ci-bot@example.com>
